//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blaugrana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int A_Id { get; set; }
        public int A_FieldId { get; set; }
        public string A_City { get; set; }
        public string A_District { get; set; }
        public string A_Street { get; set; }
        public Nullable<int> A_Number { get; set; }
        public string A_ZipCode { get; set; }
    }
}
