//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blaugrana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingOption
    {
        public int BO_Id { get; set; }
        public int BO_IdField { get; set; }
        public Nullable<System.TimeSpan> BO_MonFrom { get; set; }
        public Nullable<System.TimeSpan> BO_MonTo { get; set; }
        public Nullable<System.TimeSpan> BO_TuesFrom { get; set; }
        public Nullable<System.TimeSpan> BO_TuesTo { get; set; }
        public Nullable<System.TimeSpan> BO_WedFrom { get; set; }
        public Nullable<System.TimeSpan> BO_WedTo { get; set; }
        public Nullable<System.TimeSpan> BO_ThursFrom { get; set; }
        public Nullable<System.TimeSpan> BO_ThursTo { get; set; }
        public Nullable<System.TimeSpan> BO_FriFrom { get; set; }
        public Nullable<System.TimeSpan> BO_FriTo { get; set; }
        public Nullable<System.TimeSpan> BO_SatFrom { get; set; }
        public Nullable<System.TimeSpan> BO_SatTo { get; set; }
        public Nullable<System.TimeSpan> BO_SunFrom { get; set; }
        public Nullable<System.TimeSpan> BO_SunTo { get; set; }
        public Nullable<int> BO_MaxHourBook { get; set; }
    }
}
