//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blaugrana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int B_Id { get; set; }
        public int B_IdField { get; set; }
        public Nullable<System.DateTime> B_BookDTFrom { get; set; }
        public Nullable<System.DateTime> B_BookDTTo { get; set; }
        public string B_PersonName { get; set; }
        public string B_PersonSurname { get; set; }
        public Nullable<bool> B_ConfirmedByUser { get; set; }
        public Nullable<System.DateTime> B_InsertDT { get; set; }
        public string B_GUIDToConfirm { get; set; }
    }
}
