//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blaugrana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        public int F_Id { get; set; }
        public string F_Name { get; set; }
        public Nullable<int> F_IdAddress { get; set; }
        public Nullable<bool> F_Light { get; set; }
        public Nullable<bool> F_Rental { get; set; }
        public Nullable<bool> F_BookingPossibility { get; set; }
        public string F_PhotoPath { get; set; }
    }
}
