//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace blaugrana.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenDaysHour
    {
        public int ODH_Id { get; set; }
        public int ODH_IdField { get; set; }
        public Nullable<System.TimeSpan> ODH_MonFrom { get; set; }
        public Nullable<System.TimeSpan> ODH_MonTo { get; set; }
        public Nullable<System.TimeSpan> ODH_TuesFrom { get; set; }
        public Nullable<System.TimeSpan> ODH_TuesTo { get; set; }
        public Nullable<System.TimeSpan> ODH_WedFrom { get; set; }
        public Nullable<System.TimeSpan> ODH_WedTo { get; set; }
        public Nullable<System.TimeSpan> ODH_ThursFrom { get; set; }
        public Nullable<System.TimeSpan> ODH_ThursTo { get; set; }
        public Nullable<System.TimeSpan> ODH_FriFrom { get; set; }
        public Nullable<System.TimeSpan> ODH_FriTo { get; set; }
        public Nullable<System.TimeSpan> ODH_SatFrom { get; set; }
        public Nullable<System.TimeSpan> ODH_SatTo { get; set; }
        public Nullable<System.TimeSpan> ODH_SunFrom { get; set; }
        public Nullable<System.TimeSpan> ODH_SunTo { get; set; }
    }
}
